# nn.Module

In [4]:
from torch import nn, tensor

In [2]:
class Mymodule(nn.Module):
    def __init__(self):
        super().__init__()
        
    def forward(self, x):
        return x + 1

In [5]:
tudui = Mymodule()
print(tudui)
x = tensor([1, 2, 3])
x = tudui(x)
print(x)

Mymodule()
tensor([2, 3, 4])


## Convolution Layer

In [10]:
import torch
import torch.nn.functional as F

In [8]:
input = torch.tensor([[1, 2, 3, 4, 5],
                      [0, 1, 2, 3, 1],
                      [1, 0, 1, 0, 1],
                      [5, 2, 3, 1, 1],
                      [2, 1, 0, 1, 1]], dtype=torch.float32)
kernel = torch.tensor([[1, 0, 1],
                       [0, 1, 0],
                       [2, 0, 1]], dtype=torch.float32)

input = torch.reshape(input, (1, 1, 5, 5))
kernel = torch.reshape(kernel, (1, 1, 3, 3))

print(input.shape)
print(kernel.shape)

torch.Size([1, 1, 5, 5])
torch.Size([1, 1, 3, 3])


In [ ]:
output = F.conv2d(input, kernel, stride=1, padding=0)  # (5-3+1)/1=3
print(output)

output = F.conv2d(input, kernel, stride=2, padding=0)  # (5-3)/2+1=2
print(output)

output = F.conv2d(input, kernel, stride=1, padding=1)  # (5-3+2*1)/1+1=5
print(output)

tensor([[[[ 8.,  8., 14.],
          [15., 10., 10.],
          [ 8.,  6.,  4.]]]])
tensor([[[[ 8., 14.],
          [ 8.,  4.]]]])
tensor([[[[ 2.,  4.,  8.,  9., 11.],
          [ 2.,  8.,  8., 14.,  5.],
          [ 4., 15., 10., 10.,  6.],
          [ 6.,  8.,  6.,  4.,  3.],
          [ 4.,  9.,  3.,  5.,  2.]]]])


In [15]:
from torchvision import transforms, datasets
from torch.utils.data import DataLoader

In [31]:
dataset = datasets.CIFAR10(root='./Data/cifar10', train=False, transform=transforms.ToTensor())

dataloader = DataLoader(dataset, batch_size=32, shuffle=False)

class MyConv(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 9, 3, stride=1, padding=0)  # (32-3)/1+1=30
        
    def forward(self, x):
        x = self.conv1(x)
        return x

In [20]:
from torch.utils.tensorboard import SummaryWriter

In [33]:
conv = MyConv()
writer = SummaryWriter("dataloader")
step = 0
for data in dataloader:
    imgs, labels = data
    output = conv(imgs)
    print(imgs.shape)
    print(output.shape)
    output = torch.reshape(output,(-1, 3, 30, 30))
    writer.add_images("input", imgs, step)
    writer.add_images("output", output, step)

    step += 1

torch.Size([32, 3, 32, 32])
torch.Size([32, 9, 30, 30])
torch.Size([32, 3, 32, 32])
torch.Size([32, 9, 30, 30])
torch.Size([32, 3, 32, 32])
torch.Size([32, 9, 30, 30])
torch.Size([32, 3, 32, 32])
torch.Size([32, 9, 30, 30])
torch.Size([32, 3, 32, 32])
torch.Size([32, 9, 30, 30])
torch.Size([32, 3, 32, 32])
torch.Size([32, 9, 30, 30])
torch.Size([32, 3, 32, 32])
torch.Size([32, 9, 30, 30])
torch.Size([32, 3, 32, 32])
torch.Size([32, 9, 30, 30])
torch.Size([32, 3, 32, 32])
torch.Size([32, 9, 30, 30])
torch.Size([32, 3, 32, 32])
torch.Size([32, 9, 30, 30])
torch.Size([32, 3, 32, 32])
torch.Size([32, 9, 30, 30])
torch.Size([32, 3, 32, 32])
torch.Size([32, 9, 30, 30])
torch.Size([32, 3, 32, 32])
torch.Size([32, 9, 30, 30])
torch.Size([32, 3, 32, 32])
torch.Size([32, 9, 30, 30])
torch.Size([32, 3, 32, 32])
torch.Size([32, 9, 30, 30])
torch.Size([32, 3, 32, 32])
torch.Size([32, 9, 30, 30])
torch.Size([32, 3, 32, 32])
torch.Size([32, 9, 30, 30])
torch.Size([32, 3, 32, 32])
torch.Size([32, 9, 3

## Pooling Layer

In [51]:
torch.manual_seed(1)

In [48]:
class MyPool(nn.Module):
    def __init__(self):
        super().__init__()
        self.pool1 = nn.MaxPool2d(3, ceil_mode=True)
        
    def forward(self, x):
        return self.pool1(x)

In [54]:
pool = MyPool()
step = 0
writer = SummaryWriter("dataloader")
for data in dataloader:
    imgs, labels = data
    writer.add_images("pool_input", imgs, step)
    output = pool(imgs)
    writer.add_images("pool_output", output, step)
    step += 1
writer.close()
    

## Linear Layer

In [58]:
class MyLinear(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear1 = nn.Linear(32, 15)
        
    def forward(self, x):
        return self.linear1(x)

In [59]:
linear = MyLinear()
step = 0
writer = SummaryWriter("dataloader")
for data in dataloader:
    imgs, labels = data
    writer.add_images("pool_input", imgs, step)
    output = linear(imgs)
    writer.add_images("pool_output", output, step)
    step += 1
writer.close()
    