In [14]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision
from torch.utils.data import Dataset, DataLoader
from torch.utils.tensorboard import SummaryWriter

In [15]:
class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.sequent = nn.Sequential(
            nn.Conv2d(3, 32, 5, padding=2),
            nn.MaxPool2d(2),
            nn.Conv2d(32, 32, 5, padding=2),
            nn.MaxPool2d(2),
            nn.Conv2d(32, 64, 5, padding=2),
            nn.MaxPool2d(2),
            nn.Flatten(),
            nn.Linear(1024, 64),
            nn.Linear(64, 10)
        )
        
    def forward(self, x):
        return self.sequent(x)

In [13]:
train_set = torchvision.datasets.CIFAR10("./Data/cifar10", train=True, transform=torchvision.transforms.ToTensor())
test_set = torchvision.datasets.CIFAR10("./Data/cifar10", train=False, transform=torchvision.transforms.ToTensor())
train_data = DataLoader(train_set, batch_size=1, shuffle=False)
test_set = DataLoader(test_set, batch_size=1, shuffle=False)

In [19]:
writer = SummaryWriter("dataloader")
mymodel = MyModel()
loss = nn.CrossEntropyLoss()
step = 0
for data in train_data:
    images, labels = data
    output = mymodel(images)
    res_loss = loss(output, labels)
    print(output)
    print(labels)
    print(res_loss)

writer.close()


tensor([[ 0.1407, -0.0196,  0.1186, -0.1562,  0.0638, -0.0648, -0.0294, -0.0433,
         -0.1085,  0.0948]], grad_fn=<AddmmBackward0>)
tensor([6])
tensor(2.3361, grad_fn=<NllLossBackward0>)
tensor([[ 0.1424, -0.0014,  0.1237, -0.1519,  0.0572, -0.0664, -0.0401, -0.0232,
         -0.1149,  0.1049]], grad_fn=<AddmmBackward0>)
tensor([9])
tensor(2.2053, grad_fn=<NllLossBackward0>)
tensor([[ 0.1333, -0.0098,  0.1637, -0.1546,  0.0478, -0.0572, -0.0555, -0.0338,
         -0.1087,  0.0892]], grad_fn=<AddmmBackward0>)
tensor([9])
tensor(2.2198, grad_fn=<NllLossBackward0>)
tensor([[ 0.1330, -0.0105,  0.1177, -0.1580,  0.0633, -0.0541, -0.0422, -0.0375,
         -0.1121,  0.1021]], grad_fn=<AddmmBackward0>)
tensor([4])
tensor(2.2439, grad_fn=<NllLossBackward0>)
tensor([[ 0.1312,  0.0029,  0.1317, -0.1588,  0.0553, -0.0647, -0.0557, -0.0347,
         -0.0954,  0.1018]], grad_fn=<AddmmBackward0>)
tensor([1])
tensor(2.3056, grad_fn=<NllLossBackward0>)
tensor([[ 0.1389, -0.0066,  0.1186, -0.1504, 

KeyboardInterrupt: 

In [10]:
torch.manual_seed(1)
loss = nn.L1Loss(reduction="sum")
input = torch.randint(1,5, (1, 5),dtype=float)
target = torch.randint(1, 5, (1, 5), dtype=float)
output = loss(input, target)
print(input)
print(target)
print(output)

tensor([[2., 4., 1., 1., 4.]], dtype=torch.float64)
tensor([[2., 4., 2., 4., 1.]], dtype=torch.float64)
tensor(7., dtype=torch.float64)


In [11]:
loss_mse = nn.MSELoss()
output = loss_mse(input, target)
print(output)

tensor(3.8000, dtype=torch.float64)
